docker-compose-yaml: docker-compose.yml

environments:
  main:
    network-policies:
      - service: nginx
        projects:
        # this allows only the production environment from zs-sean-frontend to access nginx
        - name: zs-sean-frontend
          environment-type: production
  dev:
    network-policies:
      - service: nginx
        projects:
          # this allows only the development environment from zs-sean-frontend to access nginx
          - name: zs-sean-frontend
            environment-type: development